PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Experiences(id INTEGER PRIMARY KEY AUTOINCREMENT, date DATE, sense TEXT, smell TEXT, throat TEXT,  eyes TEXT, skin TEXT, tired TEXT, nausea TEXT, otherObs TEXT, windDir TEXT, windSpeed TEXT, precip TEXT, latitude REAL, longitude REAL, submitted DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE Feedback(id INTEGER PRIMARY KEY AUTOINCREMENT, feedback TEXT, submitted DATETIME DEFAULT CURRENT_TIMESTAMP);
DELETE FROM sqlite_sequence;
COMMIT;
